//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ProjectAssigned.Models
{
    internal class AllowFileSizeAttribute : Attribute
    {
        public int FileSize { get; set; }
        public string ErrorMessage { get; set; }
    }
}