//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAssigned.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreateDeveloper
    {
        public int Developer_Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Image { get; set; }
        public string Designation { get; set; }
        public System.DateTime Joindate { get; set; }
        public string Salary { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Experience { get; set; }
        public string Cv { get; set; }
        public string Bio { get; set; }
        public string Username { get; set; }
        public string UserPassword { get; set; }
    }
}
