//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAssigned.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeveloperWorkProgress
    {
        public int Workid { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string Addfile { get; set; }
        public string Status { get; set; }
        public string discription { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> Project_Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> FeedId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CreateProject CreateProject { get; set; }
        public virtual NewModule NewModule { get; set; }
        public virtual ProjectFeedback ProjectFeedback { get; set; }
    }
}
