//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAssigned.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectAssignedEntities : DbContext
    {
        public ProjectAssignedEntities()
            : base("name=ProjectAssignedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<DeveloperWorkProgress> DeveloperWorkProgresses { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Transection> Transections { get; set; }
        public virtual DbSet<CreateProject> CreateProjects { get; set; }
        public virtual DbSet<ProjectFeedback> ProjectFeedbacks { get; set; }
        public virtual DbSet<CreateDeveloper> CreateDevelopers { get; set; }
        public virtual DbSet<NewModule> NewModules { get; set; }
    }
}
