//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAssigned.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewModule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewModule()
        {
            this.DeveloperWorkProgresses = new HashSet<DeveloperWorkProgress>();
            this.ProjectFeedbacks = new HashSet<ProjectFeedback>();
        }
    
        public int ModuleId { get; set; }
        public string Budget { get; set; }
        public System.DateTime AwardDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<System.DateTime> ActualCompletedate { get; set; }
        public string Discription { get; set; }
        public string Status { get; set; }
        public Nullable<int> Assign { get; set; }
        public Nullable<int> Project_Id { get; set; }
        public string UserId { get; set; }
        public string fileupload { get; set; }
        public string Statusfeedback { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CreateProject CreateProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeveloperWorkProgress> DeveloperWorkProgresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectFeedback> ProjectFeedbacks { get; set; }
    }
}
