//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAssigned.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transection
    {
        public int TransecId { get; set; }
        public string CashType { get; set; }
        public System.DateTime Date { get; set; }
        public string Amount { get; set; }
        public string Discription { get; set; }
        public string DetailDiscription { get; set; }
    }
}
