// <auto-generated />
namespace ProjectAssigned.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class boolvalueofisactivenotnull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(boolvalueofisactivenotnull));
        
        string IMigrationMetadata.Id
        {
            get { return "202110030806513_bool value of is active not null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
